# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ndcli < Formula
  desc "NetDefense CLI tool (Development Build)"
  homepage "https://github.com/netdefense-io/ndcli-releases"
  version "0.24.0-dev.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.24.0-dev.1/ndcli_0.24.0-dev.1_darwin_amd64.tar.gz"
      sha256 "34b4c9b8e7bef87e14022dc6a59274eb395311d3016d764df0c1aaf5345c25a1"

      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.24.0-dev.1/ndcli_0.24.0-dev.1_darwin_arm64.tar.gz"
      sha256 "3f81ecf31ef2834d1046b13428e8bbd264e088bc0772efcee2dce3e91a05d6af"

      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.24.0-dev.1/ndcli_0.24.0-dev.1_linux_amd64.tar.gz"
      sha256 "ae700b5303cda10bac6117db6d366db4bf78cd29a1d0c2567d7113f1291672f5"
      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.24.0-dev.1/ndcli_0.24.0-dev.1_linux_arm64.tar.gz"
      sha256 "c31331dda4dc5d19871876f5f64fd73e7cdc99fc264f0ef15441330d5908adca"
      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
  end
end
