# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ndcli < Formula
  desc "NetDefense CLI tool (Development Build)"
  homepage "https://github.com/netdefense-io/ndcli-releases"
  version "0.16.0-dev.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.16.0-dev.1/ndcli_0.16.0-dev.1_darwin_amd64.tar.gz"
      sha256 "81f0274a75da1b6bc246bad730d905df46a444ce619cd0beaba272b162f21a87"

      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.16.0-dev.1/ndcli_0.16.0-dev.1_darwin_arm64.tar.gz"
      sha256 "d6bf8d8410b69e869919bcda56ffbc293f2476f8a1c80babc8c38f2eb33fafb5"

      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.16.0-dev.1/ndcli_0.16.0-dev.1_linux_amd64.tar.gz"
      sha256 "9d6ea385632efaf280dcfc7912719bbb3af562d3ef57bcae4f8cb837a43ea381"
      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v0.16.0-dev.1/ndcli_0.16.0-dev.1_linux_arm64.tar.gz"
      sha256 "5e7af42316da9dbb67ab5f13126c9afec194f0ef4b51485c760ae3aecb6cf144"
      def install
        bin.install "ndcli"
        bin.install "netdefense-mcp"
      end
    end
  end
end
