# This file was generated by GoReleaser. DO NOT EDIT.
cask "ndcli" do
  name "ndcli"
  desc "NetDefense CLI tool (Development Build)"
  homepage "https://github.com/netdefense-io/ndcli-releases"
  version "0.1.2-dev.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ndcli"

  on_macos do
    on_intel do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_darwin_amd64.tar.gz"
      sha256 "bdd79b8c16cdbe7f3372c46fbfccafaffc9204f40146567a8f08009c1996d253"
    end
    on_arm do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_darwin_arm64.tar.gz"
      sha256 "90615637e400c990b47b32595b9d2e2dc8fe50ba27b656bc9b49ff4023279c7b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_linux_amd64.tar.gz"
      sha256 "fbb9b3ebb2b703a82eee0cb8014034f0c59a3f25f2c9211fff92a03afd59ef16"
    end
    on_arm do
      url "https://github.com/netdefense-io/ndcli-releases/releases/download/v#{version}/ndcli_#{version}_linux_arm64.tar.gz"
      sha256 "4b65db4cb29176895d884b212ecd68d74087c5eeded2641063387e6350cf5056"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/ndcli"]
  end

  # No zap stanza required
end
